### ISSUE TITLE
Do not cause error if parent of nested field (section) is missing

### ISSUE THREAD

**Issue by adrianschmidt** [SebRollen/toml-action#13]
When using this action to access a nested field, like in the example in the readme:

```
uses: SebRollen/toml-action@v1.0.2
id: read_toml
with:
  file: 'myfile.toml'
  field: 'package.version'
```

If the `package` section of the TOML file is missing, this action produces an error.

I would like the action to instead return an empty value.

If it's useful to some users that the action indeed produces an error, the behaviour could be controlled by a parameter.
