### ISSUE TITLE
manage array fields

### ISSUE THREAD

**Issue by gpongelli** [SebRollen/toml-action#16]
Hi,
trying this action seems that TOML's array are extracted as string, having then no way to interact with it.

Is it possible to have an array object as "value" output ?

I've following situation:

pyproject.toml:
```toml
[tool.poetry]
    ...
    authors = ["Gabriele Pongelli <gpongelli@users.noreply.github.com>"]
```

github action :
```yaml
      - name: get authors from toml
        uses: SebRollen/toml-action@v1.2.0
        id: read_toml_authors
        with:
          file: 'pyproject.toml'
          field: 'tool.poetry.authors'
...
       ${{ join(steps.read_toml_authors.outputs.value, ', ') }}
```

the join seems not working, I still have `["Gabriele Pongelli <gpongelli@users.noreply.github.com>"]` as join's output instead of the expected `"Gabriele Pongelli <gpongelli@users.noreply.github.com>"` (square brackets should not be there after join, if the input is an array), so I think this action does not provide an array as output.

Can you please fix your action to handle this case ?

Thanks.
